### ISSUE TITLE
Focus distance measure for lens L085

### ISSUE THREAD

**Issue by Pepslee** [Kurokesu/SCE2-SDK#12]
From [config.yaml](https://github.com/Kurokesu/SCE2-SDK/blob/auto_calibration/03_lens_tester_gui/config.yaml)
```
  L085:
    debug_keypoints: []
    description: 25x 5.3-130mm 1/2.7"
    filter1:
      name: IR CUT
      state_off: G90 G1 A1.5 F1
      state_on: G90 G1 A0 F1
    iris:
      close: M114 P0
      open: M114 P1
    lens_sku: L085-MZFD-5.3Z130-DIRECT
    limit_sensor:
      led_off: M120 P0
      led_on: M120 P1
    motor:
      curves:
        focal_range:
          x: [-19 : 11.74]
          y: [5.27 : 143.98]
    specs:
      focal_length_max: 130
      focal_length_min: 5.3
      image_circle: 6.8
      lpm: 250
```

Lens L085.
Could you give me a hint, what are -19 and 11.74 mean ? is it min and max positions of the zoom lens in millimeters ? In this case 
 why do we have negative values (-19 ) and what zero position means ? If I understand correct, -19  corresponds to 5.27 (which is very close to min focus distance 5.3 from specs), but what is 143.98 ? there is 130 mm max focus length in specs.
And there is the similar question about focus group, are y_axis values on the [diagram](https://github.com/Kurokesu/SCE2-SDK/blob/auto_calibration/03_lens_tester_gui/screenshot.png) in millimeters and what is zero ?
Maybe you could recommend any literature for this topic ?
